/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppointmentItem: typeof import('./src/components/AppointmentItem.vue')['default']
    Button: typeof import('./src/components/UI/Button.vue')['default']
    CancelModal: typeof import('./src/components/CancelModal.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    Form: typeof import('./src/components/UI/Form.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    Input: typeof import('./src/components/UI/Input.vue')['default']
    MainList: typeof import('./src/components/MainList.vue')['default']
    Modal: typeof import('./src/components/UI/Modal/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/UI/Select.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    Wrapper: typeof import('./src/components/layouts/Wrapper.vue')['default']
  }
}
